parameters:
  - name: image
    displayName: Pool Image
    default: ubuntu-latest
    values:
    - windows-latest
    - vs2017-win2016
    - ubuntu-latest
    - ubuntu-16.04
    - macOS-latest
    - macOS-10.14
  - name: createnamespace
    type: boolean
  - name: registry
    type: string
  - name: conn
    default: serviceaccount
    displayName: Kubernetes connection

trigger: none

stages:
  - stage: GolangBuild
    displayName: Build golang application
    jobs:
      - job: DockerBuild
        displayName: Build docker image
        pool:
          vmImage: ${{ parameters.image }}
        steps:
          - task: Docker@2
            displayName: buildAndPush
            inputs:
              containerRegistry: '$(registry)'
              repository: terracloud
  - stage: DeployBackend
    displayName: Deploy into AKS
    jobs:
    - deployment: Deploy
      environment: 'dev'
      variables:
        - name: env
          value: $(Environment.Name)
        - name: imagetag
          value: $(Build.BuildId)
      pool:
        vmImage: ${{ parameters.image }}
      strategy:
        runOnce:
          deploy:
            steps:
              - task: AzureKeyVault@1
                inputs:
                  azureSubscription: 'CSP-Competency Dev-IMS App Ops-Mohammed khaja Pasha (3dc3cd1a-d5cd-4e3e-a648-b2253048af83)'
                  KeyVaultName: 'akskeyvaultcsi'
                  SecretsFilter: 'userToken'
                  RunAsPreJob: true
              - template: kubedeploy.yml
                parameters:
                  k8sconn: ${{ parameters.conn }}
                  createnamespace: ${{ parameters.createnamespace }}
                  env: $(env)
                  imagetag: $(imagetag)
                  registry: ${{ parameters.registry }}
                  token: $(usertoken)
              - template: apitesting.yml
                parameters:
                  env: $(env)
                  imagetag: $(imagetag)
                  registry: ${{ parameters.registry }}