apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: terracloudpvc${env}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: terracloudsc${env}
  resources:
    requests:
      storage: 100Mi
  volumeMode: Filesystem