kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: terracloudsc${env}
  labels:
      shareName: azurefileshare
provisioner: kubernetes.io/azure-file
reclaimPolicy: Delete
parameters:
  skuName: Standard_LRS
  location: westeurope
  storageAccount: ${storageaccount}